export const textureAliases: Record<string, string[]> = {
  grass_top: ["grass_block_top", "grass", "short_grass"],
  grass_side: ["grass_block_side", "grass_block_side_overlay", "grass_block_snow"],
  dirt: ["dirt", "coarse_dirt"],
  water: ["water_still", "water_flow"],
  glass: ["glass"],
  torch: ["torch", "glowstone"],
  short_grass: ["short_grass", "grass", "fern"],
  tall_grass: ["tall_grass", "large_fern_top", "short_grass", "grass"],
  fern: ["fern", "large_fern_top", "short_grass"],
  dandelion: ["dandelion", "yellow_flower", "sunflower_front"],
  poppy: ["poppy", "red_tulip", "rose_bush_top"],
  blue_flower: ["cornflower", "blue_orchid", "allium"],
  white_flower: ["oxeye_daisy", "azure_bluet", "white_tulip"],
  wild_bush: ["dead_bush", "azalea_leaves", "flowering_azalea_leaves", "oak_leaves"],
  reeds: ["sugar_cane", "kelp_plant", "bamboo_stalk", "tall_grass"],
  lily_pad: ["lily_pad", "mangrove_roots", "oak_leaves"],
  moss_carpet: ["moss_block", "moss_carpet", "grass_block_top"],
  mud: ["mud", "packed_mud", "dirt"],
  animal_tracks: ["mud", "coarse_dirt", "sand"],
  campfire: ["campfire_log_lit", "campfire_log", "oak_log"],
  weathered_planks: ["spruce_planks", "oak_planks"],
  weathered_beam: ["stripped_spruce_log", "spruce_log", "oak_log"],
  weathered_beam_top: ["stripped_spruce_log_top", "spruce_log_top", "oak_log_top"],
  leaves: ["oak_leaves", "oak_leaves_better", "oak_leaves_branches", "green_wool"],
  oak_leaves: ["oak_leaves", "oak_leaves_better", "oak_leaves_branches"],
  birch_leaves: ["birch_leaves", "birch_leaves_better", "birch_leaves_sparse"],
  oak_log: ["oak_log"],
  oak_log_top: ["oak_log_top", "oak_log"],
  birch_log: ["birch_log"],
  birch_log_top: ["birch_log_top", "birch_log"],
  spruce_log: ["spruce_log", "oak_log"],
  spruce_log_top: ["spruce_log_top", "spruce_log", "oak_log_top"],
  spruce_leaves: ["spruce_leaves", "spruce_leaves_better", "oak_leaves"],
  dark_oak_log: ["dark_oak_log", "oak_log"],
  dark_oak_log_top: ["dark_oak_log_top", "dark_oak_log", "oak_log_top"],
  dark_oak_leaves: ["dark_oak_leaves", "dark_oak_leaves_better", "oak_leaves"],
  snow: ["snow", "snow_block", "powder_snow", "snow_block_top"],
  crafting_table_top: ["crafting_table_top", "crafting_table_side", "oak_planks"],
  crafting_table_side: ["crafting_table_side", "oak_planks"],
  crafting_table_front: ["crafting_table_front", "crafting_table_side", "oak_planks"],
  furnace_top: ["furnace_top", "furnace_side", "cobblestone"],
  furnace_side: ["furnace_side", "cobblestone"],
  furnace_front: ["furnace_front", "furnace_side", "cobblestone"],
  furnace_front_on: ["furnace_front_on", "furnace_front", "glowstone"],
  smooth_stone: ["smooth_stone", "stone"],
  chiseled_stone_bricks: ["chiseled_stone_bricks", "stone_bricks"],
  cracked_stone_bricks: ["cracked_stone_bricks", "stone_bricks"],
  mossy_cobblestone: ["mossy_cobblestone", "cobblestone"],
  mossy_stone_bricks: ["mossy_stone_bricks", "stone_bricks"],
  end_stone_bricks: ["end_stone_bricks", "end_stone"],
  cracked_nether_bricks: ["cracked_nether_bricks", "nether_bricks"],
  chiseled_nether_bricks: ["chiseled_nether_bricks", "nether_bricks"],
  quartz_bricks: ["quartz_bricks", "quartz_block_side", "quartz_block_top"],
  quartz_pillar_top: ["quartz_pillar_top", "quartz_block_top"],
  quartz_pillar: ["quartz_pillar", "quartz_block_side", "quartz_block_top"],
  blue_ice: ["blue_ice", "packed_ice", "ice"],
  packed_ice: ["packed_ice", "ice"],
  sea_lantern: ["sea_lantern", "glowstone"],
  raw_copper_block: ["raw_copper_block", "copper_block"],
  raw_gold_block: ["raw_gold_block", "gold_block"],
  raw_iron_block: ["raw_iron_block", "iron_block"],
  tuff_bricks: ["tuff_bricks", "tuff", "stone_bricks"],
  acacia_planks: ["acacia_planks", "oak_planks"],
  spruce_planks: ["spruce_planks", "oak_planks"],
  dark_oak_planks: ["dark_oak_planks", "oak_planks"],
  jungle_planks: ["jungle_planks", "oak_planks"],
};
